services:
  - type: web
    name: sentencespeaker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k gthread --workers 1 --threads 4 --timeout 300 app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
