services:
  - type: web
    name: sentencespeaker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: OPENAI_API_KEY
        sync: false
